/**
 * Export all component includes
 */
const licenseIcons = require('./license-icons')

module.exports = {
  analytics: require('./analytics.js'),
  citation: require('./citation/index.js'),
  citationChicagoPage: require('./citation/chicago/page.js'),
  citationChicagoPublication: require ('./citation/chicago/publication.js'),
  citationChicagoPublicationContributors: require ('./citation/chicago/publication-contributors.js'),
  citationChicagoPublishers: require('./citation/chicago/publishers.js'),
  citationChicagoSite: require('./citation/chicago/site.js'),
  citationContributors: require('./citation/contributors.js'),
  citationMLAPage: require('./citation/mla/page.js'),
  citationMLAPublication: require('./citation/mla/publication.js'),
  citationMLAPublicationContributors: require('./citation/mla/publication-contributors.js'),
  citationMLAPublishers: require('./citation/mla/publishers.js'),
  citationMLASite: require('./citation/mla/site.js'),
  citationPubDate: require('./citation/pub-date.js'),
  citationPubSeries: require('./citation/pub-series.js'),
  contentsImage: require('./contents/image.js'),
  contentsItem: require('./contents/item.js'),
  contributorList: require('./contributor/list.js'),
  contributorTitle: require('./contributor/title.js'),
  copyright: require('./copyright/index.js'),
  copyrightLicensing: require('./copyright/licensing.js'),
  dublinCore: require('./page/dublin-core.js'),
  head: require('./head.js'),
  icons: require('./icons.js'),
  iconscc: require('./icons-cc.js'),
  index: require('./index.js'),
  jsonld: require('./page/jsonld.js'),
  ...licenseIcons,
  link: require('./link.js'),
  linkList: require('./link-list.js'),
  menu: require('./menu/index.js'),
  menuHeader: require('./menu/header.js'),
  menuItem: require('./menu/item.js'),
  menuList: require('./menu/list.js'),
  menuResources: require('./menu/resources.js'),
  navigation: require('./navigation.js'),
  opengraph: require('./page/opengraph.js'),
  pageButtons: require('./page-buttons.js'),
  pageTitle: require('./page-title.js'),
  pdfInfo: require('./pdf/info.js'),
  scripts: require('./scripts.js'),
  siteTitle: require('./site-title.js'),
  twitterCard: require('./page/twitter-card.js'),
}
